language: c

os:
    - osx
    - linux
    
env: DISPLAY=:99 MOZ_XVFB=1

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

notifications:
#      email:
#          - dev-automation@lists.mozilla.org
    irc:
        - "irc.mozilla.org#automation"

matrix:
    allow_failures:
      - os: osx
    exclude:
      - os: linux
        compiler: clang
      - os: osx
        compiler: gcc
