language: python

python:
    - 2.7

before_install:
    # set up linux only items
    - ./.travis/preinstall.sh

#    - sudo -H pip install virtualenv
#    - virtualenv ~/.venv
#    - source ~/.venv/bin/activate

install:
    # As long as we have invasive changes, lets get the trunk version of marionette-client
    - svn checkout https://github.com/mozilla/gecko-dev/trunk/testing/marionette/client
    - "cd client && python setup.py develop && cd .."

    - python setup.py develop
    - pip install mozdownload pep8

before_script:
    # Run pep8 on all except the checked out marionette-client folder
    - pep8 --max-line-length=99 --exclude=client .

    # Download Firefox Nightly which is compatible with the Marionette client version used 
    - mozdownload -t daily

    # install Firefox Nightly per os
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

notifications:
#      email:
#          - dev-automation@lists.mozilla.org
    irc:
        - "irc.mozilla.org#automation"

# matrix:
#    allow_failures:
#      - os: linux
