language: c

os:
    - osx
    - linux

compiler:
    - gcc

env:
    - DISPLAY=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo ':99'; fi)
      MOZ_XVFB=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo 1; fi)
      BINARY=$(if [[ $TRAVIS_OS_NAME = 'osx' ]]; then echo '/Applications/FirefoxNightly.app/Contents/MacOS/firefox'; else echo 'firefox/firefox'; fi)

before_install:
    # set up linux only items
    - ./.travis/before_install.sh

    - virtualenv ~/.venv
    - source ~/.venv/bin/activate

install:
    # As long as we have invasive changes, lets get the trunk version of marionette-client
    - svn checkout https://github.com/mozilla/gecko-dev/trunk/testing/marionette/client
    - "cd client && python setup.py develop && cd .."

    - python setup.py develop
    - pip install mozdownload pep8

before_script:
    # Run pep8 on all except the checked out marionette-client folder
    - pep8 --max-line-length=99 --exclude=client .

    # install Firefox Nightly per os
    - ./.travis/before_script.sh

script:
    #- ./.travis/run.sh
    - firefox-ui-tests --binary $BINARY

notifications:
#      email:
#          - dev-automation@lists.mozilla.org
#    irc:
#        - "irc.mozilla.org#automation"
