language: c

os:
    - osx
    - linux

compiler:
    - gcc

install:
    - ./.travis/install.sh

before_script:
    # Run pep8 on all except the checked out marionette-client folder
    - pep8 --max-line-length=99 --exclude=client .

script:
    - ./.travis/run.sh

notifications:
#      email:
#          - dev-automation@lists.mozilla.org
    irc:
        - "irc.mozilla.org#automation"

matrix:
    # allow failure on osx while we get familiar with multi-os
    allow_failures:
      - os: osx
